/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica6;

import com.sun.javafx.geom.QuadCurve2D;
import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Composite;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.Stroke;
import java.awt.font.TextAttribute;
import java.awt.geom.AffineTransform;
import java.awt.geom.Arc2D;
import java.awt.geom.Area;
import java.awt.geom.CubicCurve2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.GeneralPath;
import java.awt.geom.Line2D;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.util.Map;

/**
 *
 * @author chipi
 */
public class Lienzo extends javax.swing.JPanel {

    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        initComponents();
        punto = new Point(-500,-500);
        lineaA = new Point(-500,-500);
        lineaB = new Point(-500,-500);
        color = Color.BLACK;
        dibujo = Dibujo.enum_punto;
        relleno = Boolean.FALSE;
        vShape = new ArrayList();
        clipArea = new Ellipse2D.Float(100,100,500,500);
        ventanaClipActiva = false ;
    }
    
    public void limpiar_lienzo(){
        punto = new Point(-500,-500);
        lineaA = new Point(-500,-500);
        lineaB = new Point(-500,-500);
        color = Color.BLACK;
        dibujo = Dibujo.enum_punto;
        relleno = Boolean.FALSE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        punto = evt.getPoint();
        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        l = new Line2D.Float(evt.getPoint(), evt.getPoint());
        pAux = evt.getPoint();
        rectangulo = new Rectangle(pAux);
        
        // añadir al vector
        vShape.add(l);
        vShape.add(rectangulo);
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        l.setLine(l.getP1(), evt.getPoint());
        formMouseDragged(evt);
        repaint();
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        l.setLine(l.getP1(), evt.getPoint());
        rectangulo.setFrameFromDiagonal(pAux, evt.getPoint());
        repaint();
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        if(ventanaClipActiva){
            Point corner = evt.getPoint();
            corner.translate((int)clipArea.getWidth()/2,
            (int)clipArea.getHeight()/2);
            clipArea.setFrameFromCenter(evt.getPoint(), corner);
            this.repaint();
        }
    }//GEN-LAST:event_formMouseMoved

    private void pruebaShape(Graphics2D g2d){
        Point2D p1=new Point2D.Float(100,50);
        Point2D p2=new Point2D.Float(350,50);
        Line2D linea = new Line2D.Float(p1,p2);
        g2d.draw(linea);
        Rectangle2D rectangulito = new Rectangle2D.Float(20,40,60,80);
        g2d.draw(rectangulito);
        RoundRectangle2D round = new RoundRectangle2D.Float(20,130,60,80,90,100);
        g2d.draw(round);
        Ellipse2D elipse = new Ellipse2D.Float(20,220,30,80);
        g2d.draw(elipse);
        Arc2D arc = new Arc2D.Float(90, 70, 100, 100, 0, 90, 2);
        g2d.draw(arc);
        CubicCurve2D cc = new CubicCurve2D.Float(100, 140, 250, 180, 250, 100, 350, 140);
        g2d.draw(cc);
        //QuadCurve2D cua = new QuadCurve2D(0,0, 0, 0, 0, 0);
        //g2d.draw((Shape) cua);
        //trazo libre
        Rectangle2D rectanguloPath = new Rectangle2D.Float(220,160,60,80);
        GeneralPath gpth = new GeneralPath(rectanguloPath);// no entiendo, no hace nada
        g2d.draw(gpth);
        
        Rectangle2D rectanguloArea = new Rectangle2D.Float(120,160,60,80);
        Area arean = new Area(rectanguloArea); // idem, esto no hace nada 
        g2d.draw(arean);
    }
    @Override
     public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2d=(Graphics2D)g;
        this.setAtributos(g2d);
        if(l!=null){g2d.draw(l);}
        if(rectangulo!=null){g2d.draw(this.rectangulo);}
        
        for(Shape s:vShape){ // para dejar pintados todos los rectangulos
            g2d.draw(s);
        }
        
        if (ventanaClipActiva) {
            g2d.setClip(clipArea);
            g2d.draw(clipArea); // añadido por mi cuenta
        }
        
        //pruebaShape(g2d);
        
    }
    private void setAtributos(Graphics2D g2d){
        //Trazo
        Stroke trazo;
            float patronDiscontinuidad[] = {15.0f, 15.0f};
            trazo = new BasicStroke(10.0f,BasicStroke.CAP_ROUND,BasicStroke.JOIN_MITER, 1.0f,patronDiscontinuidad, 0.0f);
        g2d.setStroke(trazo);
            g2d.draw(new Line2D.Float(40,40,160,160));
        //Relleno
        Paint relleni;
            relleni = new Color(255, 100, 0);
        g2d.setPaint(relleni);
            g2d.draw(new Rectangle(170,40,120,120));
            g2d.fill(new Rectangle(300,40,120,120));
            // degradado
            Point pc1 = new Point(430,40), pc2 = new Point(550,160);
            relleni = new GradientPaint(pc1, Color.RED, pc2, Color.BLUE);
            g2d.setPaint(relleni);
            g2d.fill(new Rectangle(430,40,120,120));
        //Composición
        Composite composicion;
            composicion = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f);
        g2d.setComposite(composicion);
            g2d.fill(new Rectangle(190, 100, 200, 120));
        //Transformación
        Rectangle r = new Rectangle(430, 190, 120, 120);
        g2d.draw(r); //Dibujamos rectángulo sin transformación
        AffineTransform at;
        at = AffineTransform.getRotateInstance(Math.toRadians(45.0),
        r.getCenterX(),
        r.getCenterY());
        g2d.setTransform(at);
        g2d.fill(r); //Dibujamos rectángulo con transformación*/
        //Transformacion de escalado
        at = AffineTransform.getScaleInstance(0.5,0.5);
        g2d.setTransform(at);
        g2d.draw(r);
        //
        at.setToIdentity();
        at.translate(r.getCenterX(),r.getCenterY());
        at.scale(0.5,0.5);
        at.translate(-r.getCenterX(),-r.getCenterY());
        g2d.setTransform(at);
        g2d.draw(r);
        
        //para que deje de transformar
        at.setToIdentity();
        g2d.setTransform(at);
        
        //Fuente
        Font fuente;
        fuente = new Font("Arial", Font.BOLD | Font.ITALIC, 45);
        g2d.setFont(fuente);
        g2d.drawString("Hola", 30, 220);
        
        Map atributosTexto = fuente.getAttributes();
        atributosTexto.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        g2d.setFont( new Font(atributosTexto) );
        g2d.drawString("mundo", 30, 260);
        //Renderización
        RenderingHints render;
        g2d.draw(new Ellipse2D.Float(40,350,510,50)); //Elipse sin antialiasing
        render = new RenderingHints(RenderingHints.KEY_ANTIALIASING,
        RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHints(render);
        g2d.draw(new Ellipse2D.Float(40,450,510,50)); //Elipse con antialiasing
        g2d.drawString("Hola", 30, 170);
        
        render.put(RenderingHints.KEY_COLOR_RENDERING,RenderingHints.VALUE_COLOR_RENDER_QUALITY);
        
        //Recorte
        if(!ventanaClipActiva){
            Shape clipAreaAtrib;
            clipAreaAtrib = new Ellipse2D.Float(100,100,500,500);
            g2d.setClip(clipAreaAtrib);

            g2d.draw(clipAreaAtrib);
        }
    }
    public void setColor(Color color){
        this.color = color;
    }
    public Color getColor(){
        return color;
    }
    
    public void setDibujo(Enum enumerado){
        this.dibujo = enumerado;
    }
    public Enum getDibujo(){
        return dibujo;
    }
    
    public void setRelleno(Boolean booleano){
        this.relleno = booleano;
    }
    public Boolean getRelleno(){
        return relleno;
    }
    
    public void setVentanaClip(boolean activa){
        ventanaClipActiva = activa;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private Point punto, lineaA, lineaB,pAux;
    private Color color ;
    private Enum dibujo ;
    private Boolean relleno ;
    private Line2D l;
    private Rectangle2D rectangulo;
    private ArrayList<Shape> vShape;// no he podido dejar list
    private Ellipse2D clipArea;
    private boolean ventanaClipActiva;
}
