/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica4;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author chipi
 */
public class Ventana_4 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_4
     */
    public Ventana_4() {
        initComponents();
        jLabel1.setText("Etiqueta de barra de menu");
        lapiz.setSelected(true);
        this.setSize(750, 750);
        this.barra_menu.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        black = new javax.swing.JButton();
        rojo = new javax.swing.JButton();
        azul = new javax.swing.JButton();
        write = new javax.swing.JButton();
        yelow = new javax.swing.JButton();
        green = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        relleno = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        lapiz = new javax.swing.JToggleButton();
        linea = new javax.swing.JToggleButton();
        rectangulo = new javax.swing.JToggleButton();
        ovalo = new javax.swing.JToggleButton();
        lienzo2 = new practica4.Lienzo();
        Barra_de_menu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        edicion = new javax.swing.JMenu();
        barra_menu = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(149, 87));

        black.setBackground(new java.awt.Color(0, 0, 0));
        black.setPreferredSize(new java.awt.Dimension(33, 33));
        black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackActionPerformed(evt);
            }
        });
        jPanel1.add(black);

        rojo.setBackground(new java.awt.Color(255, 0, 0));
        rojo.setPreferredSize(new java.awt.Dimension(33, 33));
        rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoActionPerformed(evt);
            }
        });
        jPanel1.add(rojo);

        azul.setBackground(new java.awt.Color(0, 0, 255));
        azul.setForeground(new java.awt.Color(0, 0, 255));
        azul.setPreferredSize(new java.awt.Dimension(33, 33));
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });
        jPanel1.add(azul);

        write.setBackground(new java.awt.Color(255, 255, 255));
        write.setForeground(new java.awt.Color(255, 255, 255));
        write.setPreferredSize(new java.awt.Dimension(33, 33));
        write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeActionPerformed(evt);
            }
        });
        jPanel1.add(write);

        yelow.setBackground(new java.awt.Color(255, 255, 0));
        yelow.setForeground(new java.awt.Color(255, 255, 0));
        yelow.setPreferredSize(new java.awt.Dimension(33, 33));
        yelow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yelowActionPerformed(evt);
            }
        });
        jPanel1.add(yelow);

        green.setBackground(new java.awt.Color(0, 204, 51));
        green.setForeground(new java.awt.Color(0, 204, 51));
        green.setPreferredSize(new java.awt.Dimension(33, 33));
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActionPerformed(evt);
            }
        });
        jPanel1.add(green);

        jPanel2.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("jLabel1");
        jPanel5.add(jLabel1);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        relleno.setBackground(new java.awt.Color(204, 204, 204));
        relleno.setText("Relleno");
        relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenoActionPerformed(evt);
            }
        });
        jPanel2.add(relleno, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        lapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/iconos/Lapiz.gif"))); // NOI18N
        lapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapizActionPerformed(evt);
            }
        });
        jPanel4.add(lapiz);

        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/iconos/Linea.gif"))); // NOI18N
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });
        jPanel4.add(linea);

        rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/iconos/Rectangulo.gif"))); // NOI18N
        rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectanguloActionPerformed(evt);
            }
        });
        jPanel4.add(rectangulo);

        ovalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/iconos/Ovalo.gif"))); // NOI18N
        ovalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovaloActionPerformed(evt);
            }
        });
        jPanel4.add(ovalo);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout lienzo2Layout = new javax.swing.GroupLayout(lienzo2);
        lienzo2.setLayout(lienzo2Layout);
        lienzo2Layout.setHorizontalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        lienzo2Layout.setVerticalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo2, java.awt.BorderLayout.CENTER);

        archivo.setText("Archivo");

        nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        archivo.add(nuevo);

        abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        archivo.add(abrir);

        guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        archivo.add(guardar);

        Barra_de_menu.add(archivo);

        edicion.setText("Edicion");

        barra_menu.setSelected(true);
        barra_menu.setText("Barra de menu");
        barra_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_menuActionPerformed(evt);
            }
        });
        edicion.add(barra_menu);

        Barra_de_menu.add(edicion);

        setJMenuBar(Barra_de_menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        this.lienzo2.limpiar_lienzo();
        repaint();
    }//GEN-LAST:event_nuevoActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        this.lienzo2.setColor(Color.blue);
    }//GEN-LAST:event_azulActionPerformed

    private void rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoActionPerformed
        this.lienzo2.setColor(Color.red);
    }//GEN-LAST:event_rojoActionPerformed

    private void blackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackActionPerformed
        this.lienzo2.setColor(Color.black);
    }//GEN-LAST:event_blackActionPerformed

    private void writeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeActionPerformed
        this.lienzo2.setColor(Color.white);
    }//GEN-LAST:event_writeActionPerformed

    private void greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActionPerformed
        this.lienzo2.setColor(Color.green);
    }//GEN-LAST:event_greenActionPerformed

    private void yelowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yelowActionPerformed
        this.lienzo2.setColor(Color.yellow);
    }//GEN-LAST:event_yelowActionPerformed

    private void rellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenoActionPerformed
        if (cambio_relleno==false){
            this.lienzo2.setRelleno(true);
            cambio_relleno = true ;
        }else if (cambio_relleno == true){
            this.lienzo2.setRelleno(false);
            cambio_relleno = false ;
        }
    }//GEN-LAST:event_rellenoActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        this.lienzo2.setDibujo(Dibujo.enum_linea);
        jLabel1.setText("Linea");
        lapiz.setSelected(false);
        rectangulo.setSelected(false);
        ovalo.setSelected(false);
    }//GEN-LAST:event_lineaActionPerformed

    private void lapizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapizActionPerformed
        this.lienzo2.setDibujo(Dibujo.enum_punto);
        jLabel1.setText("Lapiz");
        linea.setSelected(false);
        rectangulo.setSelected(false);
        ovalo.setSelected(false);
    }//GEN-LAST:event_lapizActionPerformed

    private void rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectanguloActionPerformed
        this.lienzo2.setDibujo(Dibujo.enum_rectangulo);
        jLabel1.setText("Rectangulo");
        linea.setSelected(false);
        lapiz.setSelected(false);
        ovalo.setSelected(false);
    }//GEN-LAST:event_rectanguloActionPerformed

    private void ovaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovaloActionPerformed
        this.lienzo2.setDibujo(Dibujo.enum_elipse);
        jLabel1.setText("Ovalo");
        linea.setSelected(false);
        rectangulo.setSelected(false);
        lapiz.setSelected(false);
    }//GEN-LAST:event_ovaloActionPerformed

    private void barra_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_menuActionPerformed
        if(this.barra_menu.isSelected()){
            this.jLabel1.setVisible(true);
        }else{
            this.jLabel1.setVisible(false);
        }
    }//GEN-LAST:event_barra_menuActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra_de_menu;
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenu archivo;
    private javax.swing.JButton azul;
    private javax.swing.JCheckBoxMenuItem barra_menu;
    private javax.swing.JButton black;
    private javax.swing.JMenu edicion;
    private javax.swing.JButton green;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton lapiz;
    private practica4.Lienzo lienzo2;
    private javax.swing.JToggleButton linea;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JToggleButton ovalo;
    private javax.swing.JToggleButton rectangulo;
    private javax.swing.JCheckBox relleno;
    private javax.swing.JButton rojo;
    private javax.swing.JButton write;
    private javax.swing.JButton yelow;
    // End of variables declaration//GEN-END:variables
    private boolean cambio_relleno = false ;
 
}
