/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practicafinalsmm;


import java.awt.Color;
import sm.MCG.iu.Dibujo;
import sm.MCG.iu.Lienzo2DImagen;

/**
 *
 * @author mati
 */
public class ventana_interna extends javax.swing.JInternalFrame {
    
    private VentanaFinal parent = null ;
    private Enum dibujo = Dibujo.enum_punto;
    private Boolean relleno = Boolean.FALSE ;
    private int trazo_grosor = 2;
    private Boolean composicion, render, mover = Boolean.FALSE ;

    /** Creates new form NewJFrame */
    public ventana_interna(String nuevo, VentanaFinal padre ){
        super(nuevo, true, true, true, true);
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.parent=padre;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2DImagen1 = new sm.MCG.iu.Lienzo2DImagen();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lienzo2DImagen1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2DImagen1MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzo2DImagen1Layout = new javax.swing.GroupLayout(lienzo2DImagen1);
        lienzo2DImagen1.setLayout(lienzo2DImagen1Layout);
        lienzo2DImagen1Layout.setHorizontalGroup(
            lienzo2DImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        lienzo2DImagen1Layout.setVerticalGroup(
            lienzo2DImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2DImagen1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
       dibujo = lienzo2DImagen1.getDibujo();
       relleno = lienzo2DImagen1.getRelleno();
       trazo_grosor = lienzo2DImagen1.getStroke();
       composicion = lienzo2DImagen1.getCompo();
       render = lienzo2DImagen1.getRender();
       mover = lienzo2DImagen1.getEditar();
        parent.setMiVentana((Dibujo) dibujo,relleno,trazo_grosor,composicion,render, mover);
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzo2DImagen1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DImagen1MouseMoved
       try{ 
            int pixel = lienzo2DImagen1.getImage().getRGB(evt.getX(), evt.getY());
            int red = (new Color(pixel)).getRed();
            int green = (new Color(pixel)).getGreen();
            int blue = (new Color(pixel)).getBlue();
            this.parent.setEtiqueta_barra_menu(" Red "+String.valueOf(red)+" Green "+String.valueOf(green)+" Blue "+String.valueOf(blue));
       }catch(Exception ex){
           this.parent.setEtiqueta_barra_menu(" ");
       }
    }//GEN-LAST:event_lienzo2DImagen1MouseMoved

    public Lienzo2DImagen lienzo1(){
        return lienzo2DImagen1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.MCG.iu.Lienzo2DImagen lienzo2DImagen1;
    // End of variables declaration//GEN-END:variables

}
