/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica7;


import sm.MCG.iu.Dibujo;
import sm.MCG.iu.Lienzo2D;

/**
 *
 * @author chipi
 */
public class ventana_interna extends javax.swing.JInternalFrame {
    
    private Ventana7 parent = null ;
    private Enum dibujo = Dibujo.enum_punto;
    private Boolean relleno = Boolean.FALSE ;
    private int trazo_grosor = 2;
    private Boolean composicion, render, mover = Boolean.FALSE ;

    /** Creates new form NewJFrame */
    public ventana_interna(String nuevo, Ventana7 padre ){
        super(nuevo, true, true, true, true);
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.parent=padre;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo1 = new sm.MCG.iu.Lienzo2D();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
       dibujo = lienzo1.getDibujo();
       relleno = lienzo1.getRelleno();
       trazo_grosor = lienzo1.getStroke();
       composicion = lienzo1.getCompo();
       render = lienzo1.getRender();
       mover = lienzo1.getEditar();
       
        parent.setMiVentana((Dibujo) dibujo,relleno,trazo_grosor,composicion,render, mover);
        
    }//GEN-LAST:event_formInternalFrameActivated

    public Lienzo2D lienzo1(){
        return lienzo1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.MCG.iu.Lienzo2D lienzo1;
    // End of variables declaration//GEN-END:variables

}
