/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicafinalsmm;

import java.awt.image.BufferedImage;
import java.io.File;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 * Clase VentanaInternaVLCPlayer para ver los videos, hereda de VentanaInternaSM
 * @author mati
 */
public class VentanaInternaVLCPlayer extends VentanaInternaSM {

     /**
      * EmbeddedMediaPlayer de la clase, contiene el video a reproducir y le da funcionalidad.
      */
     private EmbeddedMediaPlayer vlcplayer = null;
     
     /**
      * Archivo temporal que almacena el video a reproducir.
      */
     private File fMedia;    
     
    /**
     * Constructor de la clase VentanaInternaVLCPlayer.
     * @param f, archivo donde se va a guardar el video.
     */
    public VentanaInternaVLCPlayer(File f) {
        fMedia = f;
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();
        getContentPane().add(aVisual,java.awt.BorderLayout.CENTER);
        vlcplayer = aVisual.getMediaPlayer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        play = new javax.swing.JButton();
        stop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel1.setLayout(new java.awt.GridLayout());

        jToolBar1.setRollover(true);

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica10/iconosPracticaVideo/Play.png"))); // NOI18N
        play.setToolTipText("play");
        play.setFocusable(false);
        play.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        play.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        jToolBar1.add(play);

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica10/iconosPracticaVideo/Stop.png"))); // NOI18N
        stop.setToolTipText("stop");
        stop.setFocusable(false);
        stop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        jToolBar1.add(stop);

        jPanel1.add(jToolBar1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Instanciacion de la clase VentanaInternaVLCPlayer.
     * @param f, archivo donde se va a guardar el video.
     * @return null si ya hay una insancia creada o la clase si no la hay.
     */
    public static VentanaInternaVLCPlayer getInstance(File f){
        VentanaInternaVLCPlayer v = new VentanaInternaVLCPlayer(f);
        return (v.vlcplayer!=null?v:null);
    }
    
    /**
     * Activa la reproduccion del video.
     * @param evt 
     */
    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        if (vlcplayer != null) {
            if(vlcplayer.isPlayable()){
                vlcplayer.play();
            } else {
                vlcplayer.playMedia(fMedia.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_playActionPerformed

    /**
     * Para la reproduccion del video.
     * @param evt 
     */
    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        if (vlcplayer != null) {
            if (vlcplayer.isPlaying()) {
                vlcplayer.pause();
            } else {
                vlcplayer.stop();
            }
        }
    }//GEN-LAST:event_stopActionPerformed

    /**
     * Cierra la aplicación del frame.
     * @param evt 
     */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if (vlcplayer != null) {
            try {
                vlcplayer.stop();
            } catch (Exception e) {
                System.err.println("VentanaInternaVLCPlayer: "+e);
            }
        }
    }//GEN-LAST:event_formInternalFrameClosing

    /**
     * Getter de la imagen instantanea.
     * @return BufferedImage, La instantanea seleccionada
     */
    public BufferedImage getShort(){
        return vlcplayer.getSnapshot();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton play;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
